function [fig, ax] = setupFigure()
    fig = figure('Name', 'Space Invaders', ...
                 'NumberTitle', 'off', ...
                 'MenuBar', 'none', ...
                 'Position', [100 100 800 600]);

    ax = axes('Parent', fig, ...
             'Position', [0 0 1 1], ...
             'XLim', [0 800], ...
             'YLim', [0 600]);
    axis off;
    hold on;
end